"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import { AnonAadhaarProvider } from "anon-aadhaar-react";
const inter = Inter({ subsets: ["latin"] });
import crypto from "crypto";

const app_id = BigInt(parseInt(crypto.randomBytes(20).toString("hex"), 16)); // random value.
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AnonAadhaarProvider _appId={app_id}>{children}</AnonAadhaarProvider>
      </body>
    </html>
  );
}
