import { Inter } from "next/font/google";
import "@/styles/globals.css";
const inter = Inter({ subsets: ["latin"] });
import Header from "@/components/Header";
import MoralisProviderCustom from "@/components/MoralisProvider";
import { AnonProvider } from "@/components/AnonProvider";
import Saturn from "@/components/Saturn";

// const app_id = BigInt(parseInt(crypto.randomBytes(20).toString("hex"), 16)); // random value.
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Saturn />
      <body className={inter.className}>
        <AnonProvider>
          <MoralisProviderCustom>
            <Header />
            {children}
          </MoralisProviderCustom>
        </AnonProvider>
      </body>
    </html>
  );
}
