import { Inter } from "next/font/google";
import "@/styles/globals.css";
const inter = Inter({ subsets: ["latin"] });
import Header from "@/components/Header";
import MoralisProviderCustom from "@/components/MoralisProvider";

// const app_id = BigInt(parseInt(crypto.randomBytes(20).toString("hex"), 16)); // random value.
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MoralisProviderCustom>
          <Header />
          {children}
        </MoralisProviderCustom>
      </body>
    </html>
  );
}
